apiVersion: v1
kind: Service
metadata:
  name: svc-lanchonetedobairro-api
  namespace: dev
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30200
  selector:
    app: lanchonetedobairro-api