apiVersion: v1
kind: Service
metadata:
  name: svc-lanchonetedobairro-api
  namespace: {{ .Values.namespace }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: {{ .Values.apiName }}