apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  DB_HOST: "{{ .Values.configmap.data.DB_HOST }}"
  DB_PORT: "{{ .Values.configmap.data.DB_PORT }}"
  DB_USER: "{{ .Values.configmap.data.DB_USER }}"
  DB_NAME: "{{ .Values.configmap.data.DB_NAME }}"