apiVersion: v1
kind: Service
metadata:
  name: svc-lanchonetedobairro-db
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: {{ .Values.dbName }}