apiVersion: v1                             # Versão da API Kubernetes
kind: PersistentVolume                      # Tipo de recurso: Persistent Volume (PV)
metadata:
  name: lanchonetedobairro-pv                               # Nome do PV (escolha um nome único)
spec:
  capacity:
    storage: 1Gi                           # Tamanho do armazenamento (exemplo: 10GB)
  accessModes:
    - ReadWriteOnce                         # Modo de acesso: somente leitura e escrita por um único pod
  persistentVolumeReclaimPolicy: Retain     # O que fazer com o PV após o PVC ser deletado (Retain, Recycle, Delete)
  storageClassName: manual                  # Nome da StorageClass (usado para provisionamento dinâmico), significa que você deve criar os Persistent Volumes (PVs) manualmente antes de criar os Persistent Volume Claims (PVCs)
  hostPath:                                 # Tipo de volume: hostPath (diretório no nó)
    path: /pv/data                         # Caminho no sistema de arquivos do nó