apiVersion: v1                             # Versão da API Kubernetes
kind: PersistentVolumeClaim                 # Tipo de recurso: Persistent Volume Claim (PVC)
metadata:
  name: lanchonetedobairro-pvc  
  namespace: {{ .Values.namespace }}                             # Nome do PVC (escolha um nome único)
spec:
  accessModes:
    - ReadWriteOnce                        # Modo de acesso: leitura e escrita por um único pod
  resources:
    requests:
      storage: 1Gi                         # Solicitação de armazenamento (5GB neste exemplo)
  storageClassName: manual               # Nome da StorageClass (mesmo nome que o PV usa)