apiVersion: batch/v1
kind: CronJob
metadata:
  name: remove-pedidos-cronjob
  namespace: {{ .Values.namespace }}
spec:
  schedule: "*/5 * * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: remove-pedidos
            image: "{{ .Values.removerPedidosImage.name }}:{{ .Values.removerPedidosImage.tag }}"
            env:
            - name: POSTGRES_HOST
              value: "svc-lanchonetedobairro-db"
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: DB_USER
            - name: PG_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: DB_PASSWORD
          restartPolicy: OnFailure
