version: '3.8'

services:
  lanchonetedobairro_db:
    image: mysql
    restart: always
    container_name: lanchonetedobairro_db
    volumes:
      - lanchonetedobairro:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Posgraduation@109283
    networks:
      - controledepedidos-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 3
  lanchonetedobairro_api:
    build: .
    container_name: lanchonetedobairro_api
    networks:
      - controledepedidos-network
    depends_on:
      lanchonetedobairro_db:
        condition: service_healthy
    ports:
     - '7575:80'
volumes:
  lanchonetedobairro:  

networks:
  controledepedidos-network:
    driver: bridge
