version: '3.8'

services:
  lanchonetedobairro_db:
    image: postgres
    restart: always
    container_name: lanchonetedobairro_db
    volumes:
      - lanchonetedobairro_pgsql:/var/lib/mysql
    environment:
      POSTGRES_PASSWORD: Posgraduation@109283
    ports:
      - "5432:5432"
    networks:
      - controledepedidos-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      timeout: 10s
      retries: 3
  lanchonetedobairro_api:
    build: .
    restart: always
    container_name: lanchonetedobairro_api
    networks:
      - controledepedidos-network
    depends_on:
      lanchonetedobairro_db:
        condition: service_healthy
    ports:
     - '7575:80'
volumes:
  lanchonetedobairro_pgsql:  

networks:
  controledepedidos-network:
    driver: bridge
