name: Build and test .NET

on:
  push:
    branches: [ "master", "develop", "actions", "f_*" ]
  pull_request:
    branches: [ "master", "develop", "actions", "f_*"]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  smoke_test:
    runs-on: ubuntu-latest
    needs: build_and_test
    if: github.ref == 'refs/heads/actions'
    
    steps:
      - uses: actions/checkout@v4
      - name: Run smoke tests
        env: 
          project_name: ${{ secrets.PROJECT_NAME }}
        shell: pwsh
        run: |
          ./smokeTest.ps1